### PR TITLE
Update plugin.yml

### PR DESCRIPTION
**Pull request by 301haru**
fix issue

### CODE REVIEW

**Comment by henkelmax** [comment]
Why did you remove the voice chat dependency?

**Comment by 301haru** [comment]
because that makes an error. That is about plugin dependency, not mod. So You get error in bukkit.
unknown
image is 1.16.5 but I also tested on 1.18.2

**Comment by henkelmax** [comment]
Yeah of course this is a plugin dependency. What else should it be?

**Comment by henkelmax** [comment]
Also:
image

So whats the point of this PR?

**Comment by 301haru** [comment]
https://www.spigotmc.org/wiki/plugin-yml/
I follow that spigotmc suggests,
and still I don't get it. You're meaning that there's such a plugin that called "voicechat"

**Comment by henkelmax** [comment]
Do you even know what this plugin does??

**Comment by 301haru** [comment]
Oh lol I'm stupid, my problem, sorry. had to search for it.

**Comment by 301haru** [comment]
https://www.spigotmc.org/resources/simple-voice-chat.93738/
Didn't know this exist

**Comment by henkelmax** [comment]
So you never even used this plugin before, but opened a useless PR?

**Comment by 301haru** [comment]
Why are you so aggresive. My friend was going to use this plugin and ofcourse I know what this plugin is.
There's no information in usage page, curseforge or modrinth that simple voice chat plugin exist and you have to install it for plugin addon, so is understandable to be confused.

**Pull request closed without merging**
